apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: deployment/gitops/application/argoproj
    repoURL: 'https://github.com/Tomelin/kubernetes.git'
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: core
  syncPolicy:
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
