apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: deployment/gitops/application/argoproj
    repoURL: 'https://github.com/Tomelin/kubernetes.git'
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: core
  syncPolicy:
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true

project: argoproj
source:
  repoURL: 'https://argoproj.github.io/argo-helm'
  targetRevision: 5.46.6
  helm:
    parameters:
      - name: installCRDs
        value: 'true'
    releaseName: argocd
  chart: argo-cd
destination:
  server: 'https://kubernetes.default.svc'
  namespace: argocd
syncPolicy:
  automated:
    prune: true
    allowEmpty: true
  syncOptions:
    - CreateNamespace=true

