apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: ''
    namespace: argoproj-cd
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 5.46.6
    chart: argo-cd
    helm:
      parameters:
      - name: "oidc.config"
        value: |
          name: Keycloak
          issuer: https://auth.tomelintech.com.br/realms/tomelinTech
          clientID: argocd
          clientSecret: $oidc.keycloak.clientSecret
          requestedScopes: ["openid", "profile", "email", "teste2"]
  sources: []
  project: argoproj
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
