apiVersion: v1
kind: Secret
metadata:
  name: argo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://argoproj.github.io/argo-helm
  type: helm
  name: argo
